language: python

python:
  - '3.6'

before_install:
  - sudo apt install python3-tk

install:
  - pip install pytest pytest-cov pyyaml coveralls
  - pip install -r requirements.txt --require-hashes

script:
  - py.test --cov=src tests/

after_success:
  - coveralls
